-- Junior Cards — banco pessoal
create table if not exists public.decks (
  id text primary key,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cards (
  id text primary key,
  deck_id text not null references public.decks(id) on delete cascade,
  front text not null,
  back text not null,
  note text,
  tags text[] not null default '{}',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_state (
  card_id text primary key references public.cards(id) on delete cascade,
  fsrs_card jsonb not null,
  last_grade smallint check (last_grade between 1 and 4),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_events (
  id bigint generated by default as identity primary key,
  card_id text not null references public.cards(id) on delete cascade,
  grade smallint not null check (grade between 1 and 4),
  reviewed_at timestamptz not null default now(),
  fsrs_log jsonb not null
);

create index if not exists review_events_card_id_idx on public.review_events(card_id);
create index if not exists review_events_reviewed_at_idx on public.review_events(reviewed_at desc);
create index if not exists cards_deck_id_idx on public.cards(deck_id);

alter table public.decks enable row level security;
alter table public.cards enable row level security;
alter table public.review_state enable row level security;
alter table public.review_events enable row level security;

-- Sem policies públicas: o navegador não acessa o banco diretamente.
-- As funções da Vercel usam SUPABASE_SERVICE_ROLE_KEY no servidor.

insert into public.decks (id,name,sort_order) values
('english-false-friends','🇬🇧 Inglês — Falsos cognatos',10)
on conflict (id) do update set name=excluded.name, sort_order=excluded.sort_order;

insert into public.cards (id,deck_id,front,back,note,sort_order) values
('eng-1','english-false-friends','actually','na verdade / de fato','≠ atualmente',1),
('eng-2','english-false-friends','pretend','fingir / fazer de conta','≠ pretender',2),
('eng-3','english-false-friends','parents','pais','≠ parentes',3),
('eng-4','english-false-friends','library','biblioteca','≠ livraria',4),
('eng-5','english-false-friends','college','faculdade','≠ colégio',5),
('eng-6','english-false-friends','realize','perceber / dar-se conta','≠ realizar',6),
('eng-7','english-false-friends','eventually','finalmente / com o tempo','≠ eventualmente',7),
('eng-8','english-false-friends','fabric','tecido','≠ fábrica',8),
('eng-9','english-false-friends','costume','fantasia / traje','≠ costume',9),
('eng-10','english-false-friends','lunch','almoço','≠ lanche',10),
('eng-11','english-false-friends','novel','romance (livro)','≠ novela',11),
('eng-12','english-false-friends','sensible','sensato / razoável','≠ sensível',12),
('eng-13','english-false-friends','sympathy','compaixão / solidariedade','≠ simpatia',13),
('eng-14','english-false-friends','push','empurrar','≠ puxar',14),
('eng-15','english-false-friends','pull','puxar','≠ pular',15)
on conflict (id) do update set
  deck_id=excluded.deck_id, front=excluded.front, back=excluded.back,
  note=excluded.note, sort_order=excluded.sort_order, updated_at=now();
